using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
/// <summary>
/// Using Cookies with Swagger in .NET 8
///Swagger UI, generated by Swashbuckle in ASP.NET Core projects, primarily focuses on documenting HTTP endpoints and their payloads. 
///Since cookies are part of the HTTP header, Swashbuckle does not provide a direct way to document or send cookies like it does for query parameters or request bodies.
///However, you can add support for setting cookies in Swagger UI by using Swagger operation filters to add custom headers. Here’s how you can implement an operation filter to simulate sending a cookie:
/// </summary>
public class CookieHeaderFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        operation.Parameters ??= new List<OpenApiParameter>();

        operation.Parameters.Add(new OpenApiParameter
        {
            Name = "Cookie",
            In = ParameterLocation.Header,
            Description = "Add your cookie here",
            Required = false,
            Schema = new OpenApiSchema
            {
                Type = "String"
            }
        });
    }
}
